### PR TITLE
Add support for `no_std`

### PR DESCRIPTION
**Pull request by waywardmonkeys**
This doesn't support the `scale` or `render` features yet as that needs an update to `zeno` and `yazi`.

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
If this lands, I can revise #61 to deal with `no_std`.

**Comment by waywardmonkeys** [comment]
I should add a lot of CI to this repo, including for `no_std`.

**Comment by waywardmonkeys** [comment]
Added a check for `no_std` on `x86-64-unknown-none`.

I didn't use a 32 bit target because the one I chose didn't work due to not having an `AtomicU64`.

**Review by xorgy — APPROVED** [review]

**Comment by waywardmonkeys** [comment]
I think it'll be best if #61 lands first and then I'll revise this some to support `scale`, `render` and fix some associated warnings.

**Comment by xStrom** [comment]
Swash not having `no_std` support is blocking Parley from having it, so we should really get this landed. I do agree though that #61 makes sense to land first, because the `no_std` support has changed in those deps as well.

**Review by xorgy — APPROVED** [review]

**Comment by waywardmonkeys** [comment]
@dfrg I've updated this PR to not have merge conflicts ... it gives `no_std` support but not for the `scale` or `render` features. This is still a breaking change since it requires that someone use either the `std` or `libm` features, compilation without them won't work.

**Comment by dfrg** [comment]
oops, I seem to have merged these in the wrong order causing a merge conflict (did the dep updates first)

**Comment by waywardmonkeys** [comment]
When I am awake today, I will update this so that it is fully no_std now that the deps update landed.

**Comment by waywardmonkeys** [comment]
@dfrg This is updated now. If you land #70 before this, I'll add some 32 bit no_std CI checks ... otherwise, can do that after these both land.

**Review by dfrg — APPROVED** [review]
`no_std` support has been a much requested feature since this crate was released and I really appreciate the work to get it done. 

LGTM

**Comment by dfrg** [comment]
> @dfrg This is updated now. If you land #70 before this, I'll add some 32 bit no_std CI checks ... otherwise, can do that after these both land.

I just merged #70 so I’ll leave it up to you if you whether we do the 32-bit checks here.

**Comment by waywardmonkeys** [comment]
> > @dfrg This is updated now. If you land #70 before this, I'll add some 32 bit no_std CI checks ... otherwise, can do that after these both land.
> 
> I just merged #70 so I’ll leave it up to you whether we do the 32-bit checks here.

Done. I was distracted by trying to fix Zeno's CI and wasn't looking at emails.

**Pull request merged**
