### PR TITLE
Update to current `skrifa` (0.22.3 from 0.20)

### PR DESCRIPTION
**Pull request by waywardmonkeys**

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
@dfrg This would be useful to have published for the upcoming Parley release.

**Comment by dfrg** [comment]
Should this be 0.22.3 to match the version in vello?

My thinking is we merge this, do a patch release and then follow up with the other dep bumps, no_std support and a minor release.

**Comment by waywardmonkeys** [comment]
Sure, will update this when I am at a computer, about 30 minutes.

**Comment by waywardmonkeys** [comment]
Okay, this is updated to point to 0.22.3 now.

I'm going to push some other PRs over the next little bit that can either make it in or not ...

**Comment by dfrg** [comment]
Thanks! I'll merge this and publish soon if nothing else comes in.

**Pull request merged**
