### PR TITLE
use units_per_em to scale CFF font matrix

### LINKED ISSUE #27: Some fonts are rasterised very small
I'm trying to use swash for font rasterisation in Lapce. The subpixel works great. But I do have a weird issue that some fonts are rasterised very small. The font file I've got issue with is this https://github.com/lapce/piet-wgpu/blob/master/fonts/CascadiaCode-Regular.otf

### PR DESCRIPTION
**Pull request by danielronnkvist**
Encountered a couple of fonts that were using CFF to generate paths, but their settings was a bit unusual by having the em size set to 2000. That resulted in swash rendering the fonts in half their real size. By scaling the `font_matrix` using the font's `units_per_em` instead they where rendered correctly.

I'm a bit uncertain if I should pass the metrics along the functions to where it's needed or if it's better to read the `units_per_em` by parsing the data once again. Any recommendations?

Closes #27

### CODE REVIEW

**Comment by danielronnkvist** [comment]
@dfrg could you review this when you have time?

**Comment by dfrg** [comment]
Yes, sorry for the delay. At a glance, I do think the CFF table should just read upem again rather than feeding the full metrics struct through. If you make that change, I’ll go ahead and merge.

**Comment by danielronnkvist** [comment]
@dfrg I've made an update now where the CFF table reads upem again and removed the passing of metrics.

**Comment by dfrg** [comment]
This looks great. Thank you for the fix!

**Pull request merged**
