### PR TITLE
deps: Update `yazi` and `zeno` to current

### PR DESCRIPTION
**Pull request by waywardmonkeys**

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
Doing a workaround in Parley to fix that example and then building with this version of swash still renders.

**Comment by waywardmonkeys** [comment]
@dfrg FYI

**Comment by dfrg** [comment]
I believe updating zeno is a semver breaking change since that crate is publicly re-exported. I’ve held off on doing this because I was trying to think of other breaking changes that might be valuable to include. At the very least, no_std support would be nice.

Since cosmic-text and its users depend on this, I’m trying to be conservative with breaking changes.

**Comment by waywardmonkeys** [comment]
> At the very least, no_std support would be nice.

**Comment by waywardmonkeys** [comment]
> At the very least, no_std support would be nice.

Hint received!

**Comment by waywardmonkeys** [comment]
Updated / rebased forward after 0.1.19.

**Review by xStrom — APPROVED** [review]
Let's get this landed so that work on #63 can continue. Eventually landing `no_std` support here is crucial, as it is blocking Parley from getting `no_std`.

**Comment by nicoburns** [comment]
> Thanks all and sorry for the delay. On a related note, would anyone like maintainer status on this repo to help land PRs?

I would be up for this. I wouldn't necessarily be confident reviewing more invasive changes. But I could definitely help land lint fixes, dependency bumps, CI changes, and such. Perhaps it would be good if a couple of us had permissions (@waywardmonkeys? @xorgy? @xStrom?) then we could merge each other's PRs.

**Comment by xorgy** [comment]
@dfrg I would like it, if for no other reason than to be able to label issues/pulls, and maybe go back and make tags and release notes.

**Comment by waywardmonkeys** [comment]
I can join the party too.

**Comment by xStrom** [comment]
Sure I'll take the invite too. I can do an occasional review.

**Comment by dfrg** [comment]
Thanks Kaur, sent to you as well. Looks like we’re in good shape for reviews now.

**Pull request merged**
